src/acc/urls.py
from django.urls import path, include

from . import views 

app_name = "accounts"

urlpatterns = [
    path('login', views.MyLoginView.as_view(), name="login" ),
    path('profile', views.CustomerProfileDetail.as_view(), name="profile-detail" ),
    path('profile-create', views.CustomerProfileCreate.as_view(), name="profile-create" ),
]

#  path('login', views.logtin_view, name="login" ),
    # path('item-detail/<int:pk>/', views.ItemDetail.as_view(), name="item-detail" ),
    # path('item-list/', views.ItemList.as_view(), name="item-list"),
    # path('contact-us', views.contact_form, name="contact-us" ),

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from goods import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('refs/', include('refs.urls', namespace="references")),
    path('goods/', include('goods.urls', namespace="goods")),
    path('acc/', include('acc.urls', namespace="accounts")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('', views.HomeView.as_view(), name="home" ),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# path("accounts/", include("django.contrib.auth.urls"))

src/refs/urls.py
from django.urls import path, include

from . import views 

app_name = "references"

urlpatterns = [
    path('author-list/', views.AuthorList.as_view(), name="author-list"),
    path('author-detail/<int:pk>/', views.AuthorDetail.as_view(), name="author-detail" ),
    path('author-update/<int:pk>/', views.AuthorUpdate.as_view(), name="author-update"),
    path('author-delete/<int:pk>/', views.AuthorDelete.as_view(), name="author-delete"),
    path('author-create/', views.AuthorCreate.as_view(), name="author-create"),
    path('series-list/', views.SeriesList.as_view(), name="series-list"),
    path('series-detail/<int:pk>/', views.SeriesDetail.as_view(), name="series-detail"),
    path('series-update/<int:pk>/', views.SeriesUpdate.as_view(), name="series-update"),
    path('series-create/', views.SeriesCreate.as_view(), name="series-create"),
    path('series-delete/<int:pk>/', views.SeriesDelete.as_view(), name="series-delete"),
    path('genre-list/', views.GenreList.as_view(), name="genre-list"),
    path('genre-detail/<int:pk>/', views.GenreDetail.as_view(), name="genre-detail"),
    path('genre-update/<int:pk>/', views.GenreUpdate.as_view(), name="genre-update"),
    path('genre-delete/<int:pk>/', views.GenreDelete.as_view(), name="genre-delete"),
    path('genre-create/', views.GenreCreate.as_view(), name="genre-create"),
    path('publishing-list/', views.PublishingList.as_view(), name="publishing-list"),
    path('publishing-create/', views.PublishingCreate.as_view(), name="publishing-create"),
    path('publishing-detail/<int:pk>/', views.PublishingDetail.as_view(), name="publishing-detail"),
    path('publishing-update/<int:pk>/', views.PublishingUpdate.as_view(), name="publishing-update"),
    path('publishing-delete/<int:pk>/', views.PublishingDelete.as_view(), name="publishing-delete"),
    path('seriesprivately-list/', views.SeriesPrivatelyList.as_view(), name="seriesprivately-list"),
    path('seriesprivately-detail/<int:pk>/', views.SeriesPrivatelyDetail.as_view(), name="seriesprivately-detail"),
    path('seriesprivately-update/<int:pk>/', views.SeriesPrivatelyUpdate.as_view(), name="seriesprivately-update"),
    path('seriesprivately-delete/<int:pk>/', views.SeriesPrivatelyDelete.as_view(), name="seriesprivately-delete"),
    path('seriesprivately-create/', views.SeriesPrivatelyCreate.as_view(), name="seriesprivately-create"),
]
# path('series-list/', views.series_list, name="series-list"),
# path('author-list/', views.author_list, name="author-list")
# path('series-detail/<int:serie_id>/', views.series_detail, name="series-detail"),
# path('author-detail/<int:author_id>/', views.author_detail, name="author-detail" ),
# path('series-create/', views.series_create, name="series-create"),
# path('author-create/', views.author_create, name="author-create"),
# path('author-update/<int:author_id>/', views.author_update, name="author-update"),

src/refs/models.py
from django.db import models
from django.urls import reverse, reverse_lazy

# Create your models here.

# class Region(models.Model):
#     name = models.CharField(max_length=100)
#     description = models.TextField(
#         blank=True,
#         null=True
#     )
#     def __str__(self):
#         return f"{self.pk} {self.name}"
    
class Genre(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(
        blank=True,
        null=True
    )
    def __str__(self):
        return f"{self.name} #{self.pk}"
    
    def get_absolute_url (self):
        return reverse_lazy("references:genre-detail", kwargs={"pk":self.pk})
    
class Publishing(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(
        blank=True,
        null=True
    )
    def __str__(self):
        return f"{self.name} #{self.pk}"

    def get_absolute_url (self):
        return reverse_lazy("references:publishing-detail", kwargs={"pk":self.pk})  

class Author(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(
        blank=True,
        null=True
    )
    def __str__(self):
        return f"{self.name} #{self.pk}"
    
    def get_absolute_url (self):
        return reverse_lazy("references:author-detail", kwargs={"pk":self.pk})  

class Serie(models.Model):
    author = models.ForeignKey(
        Author,
        on_delete=models.PROTECT,
        default=1,
        related_name='series'
    )
    name = models.CharField(max_length=100)
    total_number = models.PositiveIntegerField()
    description = models.TextField(
        blank=True,
        null=True
    )
    def __str__(self):
        return f"{self.name} #{self.pk}"
    
    def get_absolute_url (self):
        return reverse_lazy("references:series-detail", kwargs={"pk":self.pk})
    # return f"/series-detail/{self.pk}/"

class SeriesPrivately(models.Model):
    book_number = models.PositiveIntegerField()
    book_name = models.TextField()
    series_name = models.ForeignKey(
        Serie,
        on_delete=models.PROTECT,
        default=1,
        related_name='privately'
    )
    description = models.TextField(
        blank=True,
        null=True
    )
    def __str__(self):
        return f"{self.book_number} {self.book_name} #{self.pk}"  
    
    def get_absolute_url (self):
        return reverse_lazy("references:seriesprivately-detail", kwargs={"pk":self.pk})

    # class Meta:
    #     permissions = [
    #         ('can_view-lists', 'Can view lists')]

# class Book(models.Model):
#     name = models.CharField(max_length=100)
#     author = models.ForeignKey(
#         Author,
#         on_delete=models.PROTECT,
#         related_name='books'
#         )
#     publishing = models.ForeignKey(
#         Publishing,
#         on_delete=models.PROTECT,
#         related_name='books'
#         )
#     genre = models.ForeignKey(
#         Genre,
#         on_delete=models.PROTECT,
#         related_name='books'
#         )
#     series = models.TextField(
#         blank=True,
#         null=True
#         )
#     description = models.TextField(
#         blank=True,
#         null=True
#     )
#     price = models.DecimalField()
#     number = models.PositiveIntegerField()

#     def __str__(self):
#         return f"{self.pk} {self.name}" 

src/refs/views.py
# from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
# from django.views.decorators.csrf import csrf_exempt
# from django.conf import settings (for import files?)

from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.db.models import ProtectedError

from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin

from . import models

# Create your views here.

# def author_list(request):
#     authors = models.Author.objects.all()
#     context = {
#         'objects_list': authors,
#         'page_title': "Author list"
#     }
#     return render(request, template_name="author-list.html", context=context)
    # html = "<a href=\"/author-create/\">Create  new</a> <br><table border = \"2 \"> <tr><td>id</td><td>name</td><td>-----</td><td>-----</td></tr>"
    # for author in authors:
    #     html += f"""
    #     <tr>
    #         <td>{author.id}</td>
    #         <td>{author.name}</td>
    #         <td><a href=\"/author-detail/{author.id}\">view</a>  || <td><a href=\"/author-update/{author.id}\">update</a>
    #     </td></tr>"""
    # html += "</table>"
    # return HttpResponse(html)

class AuthorList(generic.ListView):
    model = models.Author
    fields = ['name', 'description']

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['page_title'] = "Author list"
    #     return context
    

class AuthorDetail(generic.DetailView):
    model = models.Author

class AuthorCreate(generic.CreateView):
    model = models.Author
    fields = ['name', 'description']

class AuthorUpdate(generic.UpdateView):
    model = models.Author
    fields = ['name', 'description']

class AuthorDelete(generic.DeleteView):
    model = models.Author
    success_url = reverse_lazy("references:author-list")
    
    # def delete(self, request, *args, **kwargs):
    #     try:
    #         return super().delete(request, *args, **kwargs)
    #     except ProtectedError:
    #         messages.error(request, "Deletion is not possible because there are related objects!")
    #         return redirect("references:author-detail", pk=self.get_object().pk)
            
              

# from django.shortcuts import get_object_or_404, redirect
# from django.contrib import messages
# from django.db.models import ProtectedError
#     def delete_author(request, pk):
#         author = get_object_or_404(Author, pk=pk)
#         try:
#             author.delete()
#             messages.success(request, "The author was successfully deleted!")
#         except ProtectedError:
#             messages.error(request, "Deletion is not possible because there are related objects!")
#             return redirect("references:author-detail", pk=pk)
#         return redirect("references:author-list")


# def author_detail(request, author_id):
#     # pk = ???
#     # GET http://127.0.0.1:8000/author-detail/?author_id=2&abc=12
#     # author_id = request.GET.get("author_id")
#     # URL http://127.0.0.1:8000/author-detail/2/
#     # POST http://127.0.0.1:8000/author-detail  (web-form)
#     # author_id = request.GET.get("author_id")
#     # author = models.Author.objects.get(pk=author_id)
#     # html = f"<h1> Author Detail</h1> <br>{author.pk} {author.name}<br>"
#     # series = author.series.all()
#     # if series:
#     #     html += "Series of Author: <ul>"
#     #     for serie in series:
#     #         html += f"<li> total number {serie.total_number}, title {serie.name}</Li>"
#     #     html += "</ul>"
#     # return HttpResponse(html)
#     author = models.Author.objects.get(pk=author_id)
#     context = {
#         'obj': author,
#         'page_title': f"Author detail #{author_id}"
#     }
#     return render(request, template_name="author-detail.html", context=context)

# @csrf_exempt
# def author_create(request):
#     # GET get inform
#     # POST create 1 object
#     # UPDATE (what)
#     # PATCH (what)
#     # DELETE (what)
#     # HEAD
#     if request.method == "GET":
#         html = """
#         <form method="post">
#         <input name="name"> <br>
#         <textarea name="description"> </textarea> <br>
#         <button type="submit">Save</button>
#         </form>
#         """
#         return HttpResponse(html)
#     if request.method == "POST":
#         name = request.POST.get('name')
#         description = request.POST.get('description')
#         new_author = models.Author.objects.create(name=name, description=description)
#         # /author-detail/id/
#         return HttpResponseRedirect(reverse_lazy("references:author-detail", kwargs={"author_id":new_author.id}))

# @csrf_exempt
# def author_update(request, author_id):
#     if request.method == "GET":
#         author = models.Author.objects.get(pk=author_id)
#         html = f"""
#         <form method="post">
#         <input name="name" value={author.name}> <br>
#         <textarea name="description">{author.description}</textarea> <br>
#         <button type="submit">Save</button>
#         </form>
#         """
#         return HttpResponse(html)
#     if request.method == "POST":
#         name = request.POST.get('name')
#         description = request.POST.get('description')
#         # author = models.Author.objects.get(pk=author_id)
#         # author.name = name
#         # author.description = description
#         # author.save()
#         author = models.Author.objects.filter(pk=author_id).update(
#             name=name,
#             description=description 
#         )
#         return HttpResponseRedirect(reverse_lazy("references:author-detail", kwargs={"author_id":author_id}))
    
# def series_list(request):
#     series = models.Serie.objects.all()
#     context = {
#     'objects_list': series,
#     'page_title': "Series list"
#     }
#     return render(request, template_name="series-list.html", context=context)

class GenreList(generic.ListView):
    model = models.Genre

class GenreDetail(generic.DetailView):
    model = models.Genre  

class GenreCreate(generic.CreateView):
    model = models.Genre
    fields = ['name', 'description']

class GenreUpdate(generic.UpdateView):
    model = models.Genre
    fields = ['name', 'description']

class GenreDelete(generic.DeleteView):
    model = models.Genre
    success_url = reverse_lazy("references:genre-list")

# def genre_detail(request, genre_id):
#     genre = models.Genre.objects.get(pk=genre_id)
#     context = {
#         'obj': genre,
#         'page_title': f"Genre detail #{genre_id}"
#     }
#     return render(
#         request, 
#         template_name="genre-detail.html", 
#         context=context
#         )

class PublishingList(generic.ListView):
    model = models.Publishing

class PublishingDetail(generic.DetailView):
    model = models.Publishing

class PublishingCreate(generic.CreateView):
    model = models.Publishing
    fields = ['name', 'description']

class PublishingUpdate(generic.UpdateView):
    model = models.Publishing
    fields = ['name', 'description']

class PublishingDelete(generic.DeleteView):
    model = models.Publishing
    success_url = reverse_lazy("references:publishing-list")

# def publishing_detail(request, publishing_id):
#     publishing = models.Publishing.objects.get(pk=publishing_id)
#     context = {
#         'obj': publishing,
#         'page_title': f"Publishing detail #{publishing_id}"
#     }
#     return render(
#         request, 
#         template_name="publishing-detail.html", 
#         context=context
#         )

class SeriesList(generic.ListView):
    model = models.Serie
    # context_object_name = 'series'

class SeriesDetail(generic.DetailView):
    model = models.Serie

class SeriesCreate(generic.CreateView):
    model = models.Serie
    fields = ['author', 'name', 'total_number', 'description']
    # url = "/series-list/"

class SeriesUpdate(generic.UpdateView):
    model = models.Serie
    fields = ['author', 'name', 'total_number', 'description']

class SeriesDelete(generic.DeleteView):
    model = models.Serie
    success_url = reverse_lazy("references:series-list")   

# def seriesprivately_detail(request, seriesprivately_id):
#     seriesprivately = models.SeriesPrivately.objects.get(pk=seriesprivately_id)
#     context = {
#         'obj': seriesprivately,
#         'page_title': f"Seriesprivately detail #{seriesprivately_id}"
#     }
#     return render(
#         request, 
#         template_name="seriesprivately-detail.html", 
#         context=context
#         )

class SeriesPrivatelyList(generic.ListView):
    model = models.SeriesPrivately

    def get_context_data(self, **kwargs):
        # print(self.request.user.get_all_permissions())
        context = super().get_context_data(**kwargs)
        context['page_title'] = "SeriesPrivately list"
        return context
   
    # def get_context_data(self, **kwargs):
    #     print(self.request.user)
    #     print(self.request.user.get_user_permissions())
    #     print(self.request.user.get_group_permissions())
    #     print(self.request.user.get_all_permissions())
    #     if self.request.user.has_perm('refs.add_seriesprivately'):
    #         context['hello_mesage'] = "You can add seriesprivately"
    #     else:
    #         context['hello_mesage'] = "You can NOT add seriesprivately"
    # + add {{ hello_message}} to template!
    #     context = super ).get_context_data(**kwargs)
    #     context['page_title'] = "SeriesPrivately list"
    #     return context

class SeriesPrivatelyDetail(generic.DetailView):
    model = models.SeriesPrivately

class SeriesPrivatelyCreate(PermissionRequiredMixin, generic.CreateView):
    model = models.SeriesPrivately
    fields = ['book_number', 'book_name', 'series_name', 'description']

src/refs/templates/refs/author_confirm_delete.html
{% extends "base.html" %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> Are you sure, <br>
        that you want to delete <br>
        Author #{{ object.id }} {{ object.name }}? </h1>
        {% if object.series.exists %}
        <p>Delition is not possible because there are related objects!</p>
        <a href="{% url 'references:author-detail' object.id %}" class="btn btn-outline-primary"><i class="bi bi-arrow-return-left"></i>Return to Author</a></li>
    {% else %}
        <form method="post">
            {% csrf_token %}
            <p>Are you sure, that you want to delete Author #{{ object.id }} {{ object.name }}?</p>
            <button type="submit" class="btn btn-danger"><i class="bi bi-trash-fill"></i>Delete</button>
            <a href="{% url 'references:author-detail' object.id %}" class="btn btn-outline-primary"><i class="bi bi-arrow-return-left"></i>Return to Author</a></li>
        </form>
    {% endif %}    
{% endblock MAIN_CONTENT %}

src/refs/templates/refs/author_detail.html
{% extends "base.html" %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> Author #{{ object.id }} {{ object.name }} details: </h1>
      
    <ul>
        <li><b>Author name: </b>{{ object.name }}</li>
        <li><b>Description: </b>{{ object.description }}</li>
        {% if user.is_authenticated and perms.refs.delete_author%}
        <li><b>Update this Author: </b><a href="{% url 'references:author-update' object.id %}" class="btn btn-outline-primary"><i class="bi bi-pencil-fill"></i>{{ object.name }}</a></li>
        <li><b>Delete this Author: </b><a href="{% url 'references:author-delete' object.id %}" class="btn btn-outline-primary"><i class="bi bi-trash-fill"></i>{{ object.name }}</a></li>
        {% endif %}
    </ul>


    {% if object.series.all %}
        <h2><b>Series of book by this Author: </b></h2>
        {% for serie in object.series.all %}
            <ul>
                    <li> {{serie.name}}</li>
            </ul>
        {% endfor %}
    {% else %}
        <h3><b>No series</b></h3>
    {% endif %}
    {% if user.is_authenticated and perms.refs.add_serie%}
    <a href="{% url 'references:series-create' %}" class="btn btn-outline-primary"><i class="bi bi-align-middle"></i>add a series of books</a>
    {% endif %}

{% endblock MAIN_CONTENT %}

src/refs/templates/refs/author_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> FORM </h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-success"><i class="bi bi-save2-fill"></i>Save</button>
       </form>
{% endblock MAIN_CONTENT %}

src/refs/templates/refs/genre_confirm_delete.html
{% extends "base.html" %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> Are you sure, <br>
        that you want to delete <br>
        genre #{{ object.id }} {{ object.name }}?  </h1>

        <form method="post">
            {% csrf_token %}
            <p>Are you sure, that you want to delete Genre #{{ object.id }} {{ object.name }}?</p>
            <button type="submit" class="btn btn-danger"><i class="bi bi-trash-fill"></i>Delete</button>
            <a href="{% url 'references:genre-detail' object.id %}" class="btn btn-outline-primary"><i class="bi bi-arrow-return-left"></i>Return to Genre</a></li>
        </form>
       
{% endblock MAIN_CONTENT %}

src/refs/templates/refs/genre_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> FORM </h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-success"><i class="bi bi-save2-fill"></i>Save</button>
       </form> 
{% endblock MAIN_CONTENT %}

src/refs/templates/refs/genre_list.html
{% extends "base.html" %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5">  Genre list </h1>
    <table border="2" class="table table-success table-striped">
        <tr>
            <th>ID</th>
            <th>Gener's name</th>
            <th colspan="3" style="text-align: left;">Actions</th>
        {% for obj in object_list %} 
        <tr>
            <td> #{{ obj.id }} </td>
            <td> {{ obj.name }} </td>
            <td><a href="{% url 'references:genre-detail' obj.id %}" class="btn btn-outline-primary"><i class="bi bi-eye-fill"></i>View</a></td>
            {% if user.is_authenticated and perms.refs.delete_genre%}
            <td><a href="{% url 'references:genre-update' obj.id %}" class="btn btn-outline-primary"><i class="bi bi-pencil-fill"></i></i>Update</a></td>
            <td><a href="{% url 'references:genre-delete' obj.id %}" class="btn btn-outline-primary"><i class="bi bi-trash-fill"></i>Delete</a></td>
            {% endif %}
        </tr>
        {% endfor %}
        {% if user.is_authenticated and perms.refs.add_genre %}
        <td colspan="2" style="text-align: center;">Добавить новый жанр</td>
        <td colspan="3" style="text-align: center;"><a href="{% url 'references:genre-create' %}" class="btn btn-outline-primary"><i class="bi bi-align-middle"></i></i>Create</a></td>
        {% endif %}
    </table>  
{% endblock MAIN_CONTENT %}

<!-- <table border="2" class="table table-success table-striped"></table> -->
<!-- <i class="bi bi-eye"></i>  -->

src/refs/templates/refs/publishing_confirm_delete.html
{% extends "base.html" %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> Are you sure, <br>
        that you want to delete <br>
        publishing #{{ object.id }} {{ object.name }}?  </h1>
        <form method="post">
            {% csrf_token %}
            <p>Are you sure, that you want to delete publishing #{{ object.id }} {{ object.name }}?</p>
            <button type="submit" class="btn btn-danger"><i class="bi bi-trash-fill"></i>Delete</button>
            <a href="{% url 'references:publishing-detail' object.id %}" class="btn btn-outline-primary"><i class="bi bi-arrow-return-left"></i>Return to Publishing</a></li>
        </form> 
{% endblock MAIN_CONTENT %}

src/refs/templates/refs/publishing_detail.html
{% extends "base.html" %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> Publishing #{{ object.id }} {{ object.name }} details: </h1>
    <ul>
        <li><b>Publishing's name: </b>{{ object.name }}</li>
        <li><b>Description: </b>{{ object.description }}</li>
        {% if user.is_authenticated and perms.refs.delete_publishing%}
        <li><b>Update this Publishing: </b><a href="{% url 'references:publishing-update' object.id %}" class="btn btn-outline-primary"><i class="bi bi-pencil-fill"></i>{{ object.name }}</a></li>
        <li><b>Delete this Publishing: </b><a href="{% url 'references:publishing-delete' object.id %}" class="btn btn-outline-primary"><i class="bi bi-trash-fill"></i>{{ object.name }}</a></li>
        {% endif %}
    </ul>  
{% endblock MAIN_CONTENT %}

src/refs/templates/refs/publishing_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> FORM </h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-success"><i class="bi bi-save2-fill"></i>Save</button>
       </form> 
{% endblock MAIN_CONTENT %}

src/refs/templates/refs/serie_detail.html
{% extends "base.html" %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> Serie #{{ object.id }} {{ object.name }} details: </h1>
    <ul>
        <li><b>Author name: </b>{{ object.author }}</li>
        <li><b>Author name: </b>{{ object.author.name }}</li>
        <ti><b>Author: </b><a href="{% url 'references:author-detail' object.author.id %}" class="btn btn-outline-primary"><i class="bi bi-eye-fill"></i>{{ object.author.name }}</a></li>
        <li><b>Book of seria: </b>{{ object.total_number }}</li>
        <li><b>Description: </b>{{ object.description }}</li>
        {% if user.is_authenticated and perms.refs.delete_serie%}
        <li><b>Update this seria: </b><a href="{% url 'references:series-update' object.id %}" class="btn btn-outline-primary"><i class="bi bi-pencil-fill"></i>{{ object.name }}</a></li>
        <li><b>Delete this seria: </b><a href="{% url 'references:series-delete' object.id %}" class="btn btn-outline-primary"><i class="bi bi-trash-fill"></i>{{ object.name }}</a></li>
        {% endif %}
    </ul>  
{% endblock MAIN_CONTENT %}

src/refs/templates/refs/serie_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> FORM </h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-success"><i class="bi bi-save2-fill"></i>Save</button>
       </form>  
{% endblock MAIN_CONTENT %}

src/refs/templates/refs/seriesprivately_list.html
{% extends "base.html" %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5">  </h1>
    <table border="2" class="table table-success table-striped">
        <tr>
            <th>ID</th>
            <th>Book's name</th>
            <th>Book's number of seria</th>
            <th>Series name</th>
            <th>Author of seria</th>
            <th colspan="3" style="text-align: left;">Actions</th>
        {% for obj in object_list %} 
        <tr>
            <td> #{{ obj.id }} </td>
            <td> {{ obj.book_name }} </td>
            <td> {{ obj.book_number }} </td>
            <td> {{ obj.series_name }} </td>
            <td> {{ obj.series_name.author }} </td>
            <td><a href="{% url 'references:seriesprivately-detail' obj.id %}" class="btn btn-outline-primary"><i class="bi bi-eye-fill"></i>view</a></td>
            {% if user.is_authenticated and perms.refs.delete_seriesprivately%}
            <td><a href="{% url 'references:seriesprivately-update' obj.id %}" class="btn btn-outline-primary"><i class="bi bi-pencil-fill"></i></i>Update</a></td>
            <td><a href="{% url 'references:seriesprivately-delete' obj.id %}" class="btn btn-outline-primary"><i class="bi bi-trash-fill"></i>Delete</a></td>
            {% endif %}
        </tr>
        {% endfor %}
        {% if user.is_authenticated and perms.refs.add_seriesprivately%}
        <td colspan="5" style="text-align: center;">Добавить новую книгу в серию</td>
        <td colspan="3" style="text-align: center;"><a href="{% url 'references:seriesprivately-create' %}" class="btn btn-outline-primary"><i class="bi bi-align-middle"></i></i>Create</a></td>
        {% endif %}
    </table> 
{% endblock MAIN_CONTENT %}