src/acc/urls.py
from django.urls import path, include

from . import views 

app_name = "accounts"

urlpatterns = [
    path('login', views.MyLoginView.as_view(), name="login" ),
    path('profile', views.CustomerProfileDetail.as_view(), name="profile-detail" ),
    path('profile-create', views.CustomerProfileCreate.as_view(), name="profile-create" ),
]

#  path('login', views.logtin_view, name="login" ),
    # path('item-detail/<int:pk>/', views.ItemDetail.as_view(), name="item-detail" ),
    # path('item-list/', views.ItemList.as_view(), name="item-list"),
    # path('contact-us', views.contact_form, name="contact-us" ),

src/orders/urls.py
from django.urls import path, include

from . import views 

app_name = "orders"

urlpatterns = [
    path('cart/', views.view_cart, name="view-cart"),
    path('add-item/', views.add_item_to_cart_view, name="add-item-to-cart"),
    path('evaluate/', views.evaluate_cart, name="evaluate-cart"),
    path('create-order/', views.OrderCreateView.as_view(), name="view-order-create"),
    path('created/', views.OrderFullCreatedView.as_view(), name="created-page"),
 ]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from goods import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('refs/', include('refs.urls', namespace="references")),
    path('goods/', include('goods.urls', namespace="goods")),
    path('acc/', include('acc.urls', namespace="accounts")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('', views.HomeView.as_view(), name="home" ),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# path("accounts/", include("django.contrib.auth.urls"))

src/orders/models.py
from django.db import models
from django.urls import reverse, reverse_lazy
from django.contrib.auth import get_user_model

from goods.models import Item

# Create your models here.

User = get_user_model()

class Cart(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="cards",
        blank=True,
        null=True
    )
    created = models.DateTimeField(
        auto_now_add=True,
        auto_now=False,
        verbose_name='Created date'
        )
    updated = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
        verbose_name='Modificate date'
        )

    def __str__(self):
        return f"Cart # {self.pk} for {self.user}"  
    @property
    def order_price(self):
        items = self.items.all()
        total_order_price = 0
        for item in items:
            total_order_price += item.price
        return total_order_price

class ItemInCart(models.Model):
    cart = models.ForeignKey(
        Cart,
        on_delete=models.PROTECT,
        verbose_name="Cart",
        related_name="items",
    )
    item = models.ForeignKey(
        "goods.Item",
        on_delete=models.PROTECT,
        verbose_name="Item",
        related_name="items_in_cart",
    )
    quantity = models.IntegerField(
        verbose_name="Quantity",
        default=1,
    )
    price_per_item = models.DecimalField(
        verbose_name="Price per item",
        max_digits=7,
        decimal_places=2,
    )
    @property
    def price(self):
        return self.quantity * self.price_per_item

    def __str__(self):
        return f"Item {self.item.pk} in cart {self.cart.pk}, quantity {self.quantity}"
    

class Order(models.Model):
    cart = models.OneToOneField(
        Cart,
        on_delete=models.PROTECT,
        related_name="cart",
        )
    delivery_address = models.CharField(
        max_length=500, 
        verbose_name="Адрес доставки",
        default="Товар доставить по адресу:",
        )
    phone_number = models.CharField(
        max_length=15, 
        default="+375",
        verbose_name="Номер телефона"
        )
    add_inform = models.CharField(
        max_length=300, 
        verbose_name="Дополнительная информация",
        blank=True,
        null=True
        )
    
    def __str__(self):
        return f"Order #{self.pk}"  

src/orders/forms.py
from django import forms
from django.urls import reverse, reverse_lazy

from . import models

   

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = [
            'delivery_address', 
            'phone_number',
            'add_inform'
            ]

src/orders/views.py
from django.forms import BaseModelForm
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy

# # from django.views.decorators.csrf import csrf_exempt
# # from django.conf import settings (for import files?)

# from django.shortcuts import get_object_or_404, redirect
# from django.contrib import messages
# from django.db.models import ProtectedError


from django.views import generic
# from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
# from django.contrib.auth.mixins import UserPassesTestMixin
from goods import models as book_models
# from acc import models as acc_models
from acc.models import CustomerProfile
from . import models, forms


# Create your views here.

# def get_customer_date(user):
#     # phone_number = user.profile.phone_number
#     delivery_address = user.profile.delivery_address
#     # add_inform = user.profile.add_inform
#     return delivery_address


def update_item_in_cart(key, quantity):
    item_in_cart_id = int(key.split(".")[1])
    item_in_cart = models.ItemInCart.objects.get(pk=item_in_cart_id)
    if int(quantity) == 0:
        item_in_cart.delete()
    else:
        item_in_cart.quantity = int(quantity)
        item_in_cart.save()

def get_or_create_current_cart(request):
    cart_id = request.session.get('cart_id', None)
    if request.user.is_anonymous:
        user = None
    else:
        user = request.user
    cart, created = models.Cart.objects.get_or_create(
        pk=cart_id,
        defaults={"user": user},
    )
    print("is the card was created?", created)
    print("Card ID", cart.pk)
    if created:
        request.session['cart_id'] = cart.pk
    # else:
    #     cart = models.Cart.objects.get()
    return cart


#   if not cart_id:
#         cart = models.Cart.objects.create(user = request.user)
#         request.session['cart_id'] = cart.pk
#     else:
#         cart = models.Cart.objects.get()
#     return cart_id


def create_order(request):
    cart = get_current_cart(request)
    pass

    



def get_current_cart(request):
    cart_id = request.session.get('cart_id', None)
    cart = models.Cart.objects.filter(pk=cart_id)
    if cart:
        cart = cart[0]
    else:
        cart = bool(cart)
    return cart

def add_item_to_cart(request):
    item_id = int(request.POST.get("item_id"))
    item = book_models.Item.objects.get(pk=item_id)
    price = item.price
    quantity = int(request.POST.get("quantity"))
    cart = get_or_create_current_cart(request)
    item_in_cart, created = models.ItemInCart.objects.get_or_create(
        cart=cart,
        item=item,
        defaults={
            "quantity": quantity,
            "price_per_item": price
            },
    )
    if not created:
        current_quality = item_in_cart.quantity
        item_in_cart.quantity = current_quality + quantity
        item_in_cart.save()




def view_cart(request):
    cart = get_current_cart(request)
    context = {'cart': cart}
    return render(
        request, 
        template_name="orders/view_cart.html", 
        context=context,
        )

def evaluate_cart(request):
    if request.method == "POST":
        print(request.POST)
        action = None
        for key, value in request.POST.items():
            if key[0:4] == "quan":
                update_item_in_cart(key, value)
            if key[0:4] == "acti":
                action = value
        if action == "update":          
            return HttpResponseRedirect(reverse_lazy('orders:view-cart'))
        return HttpResponseRedirect(reverse_lazy('orders:view-order-create'))



def add_item_to_cart_view(request):
    if request.method == "POST":
        add_item_to_cart(request)
    return HttpResponseRedirect(reverse_lazy('orders:view-cart'))

class OrderCreateView(generic.CreateView):
    model = models.Order
    form_class = forms.OrderCreateForm
    template_name = "orders/create_order.html"
    success_url = reverse_lazy('orders:created-page')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart'] = get_current_cart(self.request)
        return context
    
    def get_form(self, **kwargs):
        form = super().get_form(**kwargs)
        profile = None
        if self.request.user.is_authenticated:
            try:
                profile = self.request.user.profile
            except CustomerProfile.DoesNotExist:
                profile = None
        if profile:
            form.fields["phone_number"].initial = profile.phone_number
            form.fields["delivery_address"].initial = profile.delivery_address
            form.fields["add_inform"].initial = profile.add_inform              
        return form
    


        # print(dir(form.fields['phone_number']))

    # def get_form(self, **kwargs):
    #     form = super().get_form(**kwargs)
    #     form.fields["phone_number"].initial = get_customer_date(self.request.user)
    #     form.fields["delivery_address"].initial = get_customer_date(self.request.user)
    #     form.fields["add_inform"].initial = get_customer_date(self.request.user)
    #     return form
    #     try:
        #     form.fields["phone_number"].initial = get_customer_date(self.request.user)
        #     form.fields["delivery_address"].initial = get_customer_date(self.request.user)
        #     form.fields["add_inform"].initial = get_customer_date(self.request.user)
        # except Profile.DoesNotExist:
        #     pass
        # return form



    def form_valid(self, form):
        order = form.save(commit=False)
        order.cart = get_current_cart(self.request)
        order.save()
        self.object = order
        return HttpResponseRedirect(self.get_success_url())
    

class OrderFullCreatedView(generic.TemplateView):
    template_name = "orders/created.html"

    def get(self, request, *args, **kwargs):
        if 'cart_id' in request.session:
            del request.session['cart_id']
        return super().get(request, *args, **kwargs)
    
    # context = self.get_context_data(**kwargs)
    #     return self.render_to_response(context)

src/orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> Your Order: </h1>
   
    <h3>Items in your order:</h3>

    <table class="table table-success table-striped">
        <tr>
            <th>Item</th>
            <th>Price per item </th>
            <th>Quantity</th>
            <th>Price</th>
            <th colspan="1" style="text-align: left;">Actions</th>
        {% for item_in_cart in cart.items.all %} 
        <tr>
            <td> {{ item_in_cart.item.title }} </td>
            <td> {{ item_in_cart.price_per_item }} </td>
            <td> 
                <div class="mb-3">
                   {{ item_in_cart.quantity }}
                </div>
            </td>
            <td> {{ item_in_cart.price }} </td>
            <td> #</td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="3" style="text-align: left;"><b>Order price:</b></td>
            <td colspan="2" style="text-align: left;"><b>{{cart.order_price}}</b></td>
        </tr>
    </table> 

    <hr>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}

        <button type="submit"  class="btn btn-success"><i class="bi bi-align-middle"></i>Create</button>   
        </form>
    
{% endblock MAIN_CONTENT %}

src/orders/templates/orders/created.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> Your order was created! Our managers will call you soon! </h1>
    
{% endblock MAIN_CONTENT %}

src/orders/templates/orders/view_cart.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> Your cart: </h1>
    {% if cart %}
    <ul>
        <li>Your cart id is {{cart.id}}</li>
        <li>Created {{cart.created}}</li>
        <li>Updated {{cart.updated}}</li>
    </ul>
    <h3>Items in cart:</h3>
    <form action="{% url 'orders:evaluate-cart'%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
    <table class="table table-success table-striped">
        <tr>
            <th>Item</th>
            <th>Price per item </th>
            <th>Quantity</th>
            <th>Price</th>
            <th colspan="1" style="text-align: left;">Actions</th>
        {% for item_in_cart in cart.items.all %} 
        <tr>
            <td> {{ item_in_cart.item.title }} </td>
            <td> {{ item_in_cart.price_per_item }} </td>
            <td> 
                <div class="mb-3">
                    <input type="number" 
                    name="quantity.{{ item_in_cart.pk }}"
                    class="form-control"  
                    step="1" 
                    value="{{ item_in_cart.quantity }}"
                    min="0">
                </div>
            </td>
            <td> {{ item_in_cart.price }} </td>
            <td> #</td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="3" style="text-align: left;"><b>Order price:</b></td>
            <td colspan="2" style="text-align: left;"><b>{{cart.order_price}}</b></td>
        </tr>
    </table> 
    <button type="submit" name="action"  value="update" class="btn btn-primary"><i class="bi bi-pencil-fill"></i>Update</button>
    <button type="submit" name="action" value="create" class="btn btn-success"><i class="bi bi-align-middle"></i>Create order</button>   
    </form>
    {% else %}
    <h2> Your cart is empty! </h2>
    {% endif %}
{% endblock MAIN_CONTENT %}