src/acc/urls.py
from django.urls import path, include

from . import views 

app_name = "accounts"

urlpatterns = [
    path('login', views.MyLoginView.as_view(), name="login" ),
    path('profile', views.CustomerProfileDetail.as_view(), name="profile-detail" ),
    path('profile-create', views.CustomerProfileCreate.as_view(), name="profile-create" ),
]

#  path('login', views.logtin_view, name="login" ),
    # path('item-detail/<int:pk>/', views.ItemDetail.as_view(), name="item-detail" ),
    # path('item-list/', views.ItemList.as_view(), name="item-list"),
    # path('contact-us', views.contact_form, name="contact-us" ),

src/goods/urls.py
from django.urls import path, include

from . import views 

app_name = "goods"

urlpatterns = [
    path('item-create/', views.ItemCreate.as_view(), name="item-create"),
    path('item-detail/<int:pk>/', views.ItemDetail.as_view(), name="item-detail" ),
    path('item-update/<int:pk>/', views.ItemUpdate.as_view(), name="item-update" ),
    path('item-list/', views.ItemList.as_view(), name="item-list"),
    path('item-delete/<int:pk>/', views.ItemDelete.as_view(), name="item-delete" ),
    path('contact-us', views.contact_form, name="contact-us" ),
]

# path('basic-form', views.basic_form, name="basic-form" ),
#  path('author-list/', views.AuthorList.as_view(), name="author-list"),
#     path('author-detail/<int:pk>/', views.AuthorDetail.as_view(), name="author-detail" ),
#     path('author-update/<int:pk>/', views.AuthorUpdate.as_view(), name="author-update"),
#     path('author-delete/<int:pk>/', views.AuthorDelete.as_view(), name="author-delete"),
#     path('author-create/', views.AuthorCreate.as_view(), name="author-create"),

src/orders/urls.py
from django.urls import path, include

from . import views 

app_name = "orders"

urlpatterns = [
    path('cart/', views.view_cart, name="view-cart"),
    path('add-item/', views.add_item_to_cart_view, name="add-item-to-cart"),
    path('evaluate/', views.evaluate_cart, name="evaluate-cart"),
    path('create-order/', views.OrderCreateView.as_view(), name="view-order-create"),
    path('created/', views.OrderFullCreatedView.as_view(), name="created-page"),
 ]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from goods import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('refs/', include('refs.urls', namespace="references")),
    path('goods/', include('goods.urls', namespace="goods")),
    path('acc/', include('acc.urls', namespace="accounts")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('', views.HomeView.as_view(), name="home" ),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# path("accounts/", include("django.contrib.auth.urls"))

src/refs/urls.py
from django.urls import path, include

from . import views 

app_name = "references"

urlpatterns = [
    path('author-list/', views.AuthorList.as_view(), name="author-list"),
    path('author-detail/<int:pk>/', views.AuthorDetail.as_view(), name="author-detail" ),
    path('author-update/<int:pk>/', views.AuthorUpdate.as_view(), name="author-update"),
    path('author-delete/<int:pk>/', views.AuthorDelete.as_view(), name="author-delete"),
    path('author-create/', views.AuthorCreate.as_view(), name="author-create"),
    path('series-list/', views.SeriesList.as_view(), name="series-list"),
    path('series-detail/<int:pk>/', views.SeriesDetail.as_view(), name="series-detail"),
    path('series-update/<int:pk>/', views.SeriesUpdate.as_view(), name="series-update"),
    path('series-create/', views.SeriesCreate.as_view(), name="series-create"),
    path('series-delete/<int:pk>/', views.SeriesDelete.as_view(), name="series-delete"),
    path('genre-list/', views.GenreList.as_view(), name="genre-list"),
    path('genre-detail/<int:pk>/', views.GenreDetail.as_view(), name="genre-detail"),
    path('genre-update/<int:pk>/', views.GenreUpdate.as_view(), name="genre-update"),
    path('genre-delete/<int:pk>/', views.GenreDelete.as_view(), name="genre-delete"),
    path('genre-create/', views.GenreCreate.as_view(), name="genre-create"),
    path('publishing-list/', views.PublishingList.as_view(), name="publishing-list"),
    path('publishing-create/', views.PublishingCreate.as_view(), name="publishing-create"),
    path('publishing-detail/<int:pk>/', views.PublishingDetail.as_view(), name="publishing-detail"),
    path('publishing-update/<int:pk>/', views.PublishingUpdate.as_view(), name="publishing-update"),
    path('publishing-delete/<int:pk>/', views.PublishingDelete.as_view(), name="publishing-delete"),
    path('seriesprivately-list/', views.SeriesPrivatelyList.as_view(), name="seriesprivately-list"),
    path('seriesprivately-detail/<int:pk>/', views.SeriesPrivatelyDetail.as_view(), name="seriesprivately-detail"),
    path('seriesprivately-update/<int:pk>/', views.SeriesPrivatelyUpdate.as_view(), name="seriesprivately-update"),
    path('seriesprivately-delete/<int:pk>/', views.SeriesPrivatelyDelete.as_view(), name="seriesprivately-delete"),
    path('seriesprivately-create/', views.SeriesPrivatelyCreate.as_view(), name="seriesprivately-create"),
]
# path('series-list/', views.series_list, name="series-list"),
# path('author-list/', views.author_list, name="author-list")
# path('series-detail/<int:serie_id>/', views.series_detail, name="series-detail"),
# path('author-detail/<int:author_id>/', views.author_detail, name="author-detail" ),
# path('series-create/', views.series_create, name="series-create"),
# path('author-create/', views.author_create, name="author-create"),
# path('author-update/<int:author_id>/', views.author_update, name="author-update"),

src/goods/models.py
from django.db import models
from django.urls import reverse, reverse_lazy

from refs.models import Author, Genre, Publishing, Serie

class Item(models.Model):
    title = models.CharField(
        verbose_name='Название книги',
        max_length=200
        )
    cover = models.ImageField(
        verbose_name='Фото обложки',
        upload_to='item_covers/%Y/%m/%d/'
    )
    price = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        verbose_name='Цена, BYN',
        )
    author = models.ManyToManyField(
        Author,
        verbose_name='Автор',
        related_name='books',
        )
    series = models.ForeignKey(
        Serie,
        on_delete=models.SET_NULL,
        verbose_name='Название серии',
        related_name='books_in_seria',
        blank=True,
        null=True
        )
    genre = models.ManyToManyField(
        Genre,
        verbose_name='Жанр',
        related_name='books_in_genre',
        )
    publishing_year = models.PositiveSmallIntegerField(
        verbose_name='Год издания',
        blank=True,
        null=True
    )
    pages = models.PositiveIntegerField(
        verbose_name='Количество страниц',
        blank=True,
        null=True
    )
    binding = models.CharField(
        verbose_name="",
        default='Твердый',
        max_length=200,
        blank=True,
        null=True
        )
    format = models.CharField(
        max_length=100,
        default='70x90/16',
        verbose_name="Формат",
        blank=True,
        null=True
    )
    isbn = models.CharField(
        verbose_name='ISBN',
        max_length=13,
        blank=True,
        null=True
        )
    weight = models.PositiveSmallIntegerField(
        default=15,
        verbose_name='Вес, гр'
    )
    age_restrictions = models.CharField(
        max_length=5,
        verbose_name='Возрастные ограничения',
        blank=True,
        null=True
    )
    publishing = models.ForeignKey(
        Publishing,
        on_delete=models.SET_NULL,
        verbose_name='Издательство',
        related_name='books_published',
        blank=True,
        null=True
        )
    item_in_stock = models.PositiveSmallIntegerField(
        default=1,
        verbose_name='Количество книг в наличии'
    )
    active = models.BooleanField(
        default=True,
        verbose_name='Достуно для заказа'
    )
    rating = models.PositiveSmallIntegerField(
        default=1,
        verbose_name='Рейтинг'
    )
    date_added = models.DateTimeField(
        auto_now_add=True,
        auto_now=False,
        verbose_name='Дата внесения в каталог'
        )
    date_last_modified = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
        verbose_name='Дата последнего изменения карточки'
        )

    def __str__(self):
        return f"#{self.pk} {self.title}" 
    
    def get_absolute_url (self):
        return reverse_lazy("goods:item-detail", kwargs={"pk":self.pk})

# class DummiItem(models.Model):
#     title = models.CharField(
#         verbose_name='Название книги',
#         max_length=200
#         )
#     cover = models.ImageField(
#         verbose_name='Фото обложки',
#         upload_to='item_covers/%Y/%m/%d/'
#     )
#     def __str__(self):
#         return f"#{self.pk} {self.title}" 
    
#     def get_absolute_url (self):
#         return reverse_lazy("goods:item-detail", kwargs={"pk":self.pk})

src/goods/forms.py
from django import forms
from django.urls import reverse, reverse_lazy
from django.core.exceptions import ValidationError

from . import models


def dennis_validator(value):
    if value[0:6] != "Dennis":
        raise ValidationError("Name must start with Dennis!")
    
# from django.core.exceptions import ValidationError
# from django.utils.translation import gettext_lazy as _
# def validate_even(value):
#     if value % 2 != 0:
#         raise ValidationError(
#             _("%(value)s is not an even number"),
#             params={"value": value},
#         )


class ContactForm(forms.Form):
    name = forms.CharField(
        max_length=123,
        min_length=1,
        required=True,
        label="Enter your name!",
        )
    message = forms.CharField(
        widget=forms.Textarea,
        required=True,
        label="Leave your message!"
        )
    def clean(self, *args, **kwargs):
        cleaned_data = super().clean(*args, **kwargs)
        name = cleaned_data["name"]
        message = cleaned_data["message"]
        if name[0:6] == "Dennis" and message[0:5] != "Hello":
                raise ValidationError("If the name is Dennis, message must start with Hello!")
        return cleaned_data
 
        
#    subject = forms.CharField(max_length=100)
#     message = forms.CharField(widget=forms.Textarea)
#     sender = forms.EmailField()
#     cc_myself = forms.BooleanField(required=False)

# можно вписать валидар прямо в модель или форму(класс)
# здесь выполняется проверка поля 'recipients':
# def clean_recipients(self):
#         data = self.cleaned_data["recipients"]
#         if "fred@example.com" not in data:
#             raise ValidationError("You have forgotten about Fred!")

#         # Always return a value to use as the new cleaned data, even if
#         # this method didn't change it.
#         return data


# class DummiItemCreateForm(forms.ModelForm):
#     class Meta:
#          newfield with my parametrs = describe new field
#          model = models.DummiItem
#          fields = ['title', 'cover', 'newfield with my parametrs']


# class BasicForm(forms.Form):
#     name = forms.CharField(
#         max_length=123,
#         min_length=1,
#         required=True,
#         label="Enter your name!",
#         )

src/goods/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from . import models, forms


class ItemCreate(generic.CreateView):
    model = models.Item
    fields = [
        'title', 'cover', 'price', 'author', 'series', 'genre', 
        'publishing_year', 'pages', 'binding', 'format', 'isbn',
        'weight', 'age_restrictions', 'publishing', 'item_in_stock',
        'active', 'rating'
        ]

class ItemUpdate(generic.UpdateView):
    model = models.Item
    fields = [
        'title', 'cover', 'price', 'author', 'series', 'genre', 
        'publishing_year', 'pages', 'binding', 'format', 'isbn',
        'weight', 'age_restrictions', 'publishing', 'item_in_stock',
        'active', 'rating'
        ]
    
class ItemDetail(generic.DetailView):
    model = models.Item

class ItemList(generic.ListView):
    model = models.Item

class ItemDelete(generic.DeleteView):
    model = models.Item
    success_url = reverse_lazy("goods:item-list")


def contact_form(request):
    if request.method == "GET":
        form = forms.ContactForm()
        context = {"form": form}
        return render(
        request, 
        template_name="goods/contact_form.html",
        context=context)
    if request.method == "POST":
        form = forms.ContactForm(request.POST)
        if form.is_valid():
            # send_email_to_manager(date)
            pass
        else:
             context = {"form": form}
             return render(
                 request, 
                 template_name="goods/contact_form.html",
                 context=context
                 )
        return HttpResponseRedirect("/mess_send")
    
    
    
    # return HttpResponseRedirect(reverse_lazy("goods:item-detail"))

# def basic_form(request):
#     if request.method == "GET":
#         form = forms.BasicForm()
#         context = {"form": form}
#         return render(
#         request, 
#         template_name="goods/basic_form.html",
#         context=context)  



class HomeView(generic.TemplateView):
    template_name = "goods/index.html"

src/goods/templates/goods/contact_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> Contact form </h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <button type="submit" class="btn btn-primary btn-lg"><i class="bi bi-envelope-fill"></i>Send message</button>
        </form>
{% endblock MAIN_CONTENT %}

      

<!-- <!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-widht, initial-scale=1.0">
        <title>{{ page_title }}</title>
    </head>
    <body>
        <h1>Contact form</h1>
        <h1>{{ heading }}</h1>
        <p>{{ message}}</p>
       <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Send</button>
       </form>
    </body>
</html> -->

src/goods/templates/goods/index.html
{% extends "base.html" %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5" style="text-align: center;"> WELCOM to DUMMY BOOK STORE! </h1>

<style>
    body{
        background-color: green;
    }
</style> 
<a href="{% url 'goods:item-list'%}" class="btn btn-primary"><i class="bi bi-arrow-return-left"></i>List of Book</a>
<a href="{% url 'references:author-list'%}" class="btn btn-primary"><i class="bi bi-arrow-return-left"></i>List of Author</a>
<a href="{% url 'references:series-list'%}" class="btn btn-primary"><i class="bi bi-arrow-return-left"></i>List of series book</a>
<a href="{% url 'references:genre-list'%}" class="btn btn-primary"><i class="bi bi-arrow-return-left"></i>List of genre</a>
<a href="{% url 'references:publishing-list'%}" class="btn btn-primary"><i class="bi bi-arrow-return-left"></i>List of publishing</a>
<a href="{% url 'accounts:profile-create'%}" class="btn btn-primary"><i class="bi bi-arrow-return-left"></i>Profile create</a>
<a href="{% url 'orders:view-cart'%}" class="btn btn-primary"><i class="bi bi-arrow-return-left"></i>Cart</a>


<div>

    </div>
{% endblock MAIN_CONTENT %}

src/goods/templates/goods/item_confirm_delete.html
{% extends "base.html" %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> Are you sure, <br>
        that you want to delete <br>
       book #{{ object.id }} {{ object.title }}?</h1>
       <form method="post">
        {% csrf_token %}
        <p>Are you sure, that you want to delete Book #{{ object.id }} {{ object.title }}?</p>
        <button type="submit" class="btn btn-danger"><i class="bi bi-trash-fill"></i>Delete</button>
        <a href="{% url 'goods:item-detail' object.id %}" class="btn btn-outline-primary"><i class="bi bi-arrow-return-left"></i>Return to Book</a></li>
    </form>   

{% endblock MAIN_CONTENT %}

src/goods/templates/goods/item_detail.html
{% extends "base.html" %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> Book #{{ object.id }} {{ object.title }} details: </h1>
     <li><b>Book title: </b>{{ object.title }}</li> 
    <p>Авторы:</p>
    <ul>
       {% for author in object.author.all %}
        <li> {{ author.name }}</li>
        {% empty %}
        <li> Автор не указан</li>
        {%endfor%}
    </ul>
    <ul>
      {% if user.is_authenticated and perms.goods.delete_item%}
      <li><b>Update this Book: </b><a href="{% url 'goods:item-update' object.id %}" class="btn btn-outline-primary"><i class="bi bi-pencil-fill"></i>{{ object.title }}</a></li>
      <li><b>Delete this Book: </b><a href="{% url 'goods:item-delete' object.id %}" class="btn btn-outline-primary"><i class="bi bi-trash-fill"></i>{{ object.title }}</a></li> 
      {% endif %} 
  </ul>
    <div class="card" style="width: 18rem;">
        <img src="{{ object.cover.url }}" class="card-img-top" alt="">
        <div class="card-body">
          <h5 class="card-title">{{ object.title }}</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
        <div class="card-body">
          <a href="#" class="card-link">Card link</a>
          <a href="#" class="card-link">Another link</a>
        </div>
      </div>

      <h3>Add to the cart:</h3>
      <form action="{% url 'orders:add-item-to-cart' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="item_id" value="{{ object.id}}"
      <h2 class="mb-3">
          <label class="form-label">Quantity:</label>
          <input type="number" name="quantity" class="form-control"  step="1" min="1">
          <div class="form-text">Pick a number</div>
      </h2>
        <button type="submit" class="btn btn-primary"><i class="bi bi-align-middle"></i>Add to cart</button>
       </form>
    
{% endblock MAIN_CONTENT %}

src/goods/templates/goods/item_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> FORM </h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-success"><i class="bi bi-save2-fill"></i>Save</button>
       </form>
{% endblock MAIN_CONTENT %}

src/goods/templates/goods/item_list.html
{% extends "base.html" %}


{% block MAIN_CONTENT %} 
    <h1 class="mt-5"> Book list </h1>
    <table border="2" class="table table-success table-striped">
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Authors</th>
            <th>Genre</th>
            <th>Series</th>
            <th>Price</th>
            <th>Active</th>
            <th>Cover</th>
            <th colspan="3" style="text-align: left;">Actions</th>
        {% for obj in object_list %} 
        <tr>
            <td> #{{ obj.id }} </td>
            <td> {{ obj.title }} </td>
            <td> 
                <ul>
                {% for author in obj.author.all %}
                 <li> {{ author.name }}</li>
                 {%endfor%}
                </ul>
            </td>
            <td> 
                <ul>
                {% for genre in obj.genre.all %}
                 <li> {{ genre.name }}</li>
                 {%endfor%}
                </ul>
            </td>
            <td> {{ obj.series }} </td>
            <td>{{ obj.price }}</td>
            <td>{{ obj.active }}</td>
            <td><img src="{{ obj.cover.url }}" width="80" height="105" alt=""></td>
            <td><a href="{% url 'goods:item-detail' obj.id %}" class="btn btn-outline-primary"><i class="bi bi-eye-fill"></i>view</a></td>
            {% if user.is_authenticated and perms.goods.delete_item%}
            <td><a href="{% url 'goods:item-update' obj.id %}" class="btn btn-outline-primary"><i class="bi bi-pencil-fill"></i></i>Update</a></td>
            <td><a href="{% url 'goods:item-delete' obj.id %}" class="btn btn-outline-primary"><i class="bi bi-trash-fill"></i>Delete</a></td>
            {% endif %}
        </tr>
        {% endfor %}
        {% if user.is_authenticated and perms.goods.add_item%}
        <td colspan="8" style="text-align: center;">Добавить новую книгу</td>
        <td colspan="3" style="text-align: center;"><a href="{% url 'goods:item-create' %}" class="btn btn-outline-primary"><i class="bi bi-align-middle"></i></i>Create</a></td>
        {% endif %}
    </table>  
{% endblock MAIN_CONTENT %}



<!-- <th>Book_in_stoke</th>
<th>Reting</th>
<td>{{ obj.item_in_stock }}</td>
<td>{{ obj.rating }}</td> -->
<!-- <td><img src="{{ obj.cover.url }}" width="80" height="105" alt=""></td> -->
<!-- <a href = "{{ obj.cover.url }}" target="_blank"></a>
<img src= "{{ obj.cover.url }}" alt="Thumbnail" style="width: 40 xp; height: 80 xp;"></a> -->

<!-- 
<th>Price</th>
<th>Book_in_stoke</th>
<th>Active</th>
<th>Reting</th>
<th>-----</th> -->

<!-- <ul>
    {% for author in obj.author.all %}
     <li> {{ author.name }}</li>
     {% empty %}
     <li> Автор не указан</li>
     {%endfor%}
    </ul> -->

src/goods/templates/goods/mess_send.html
{% extends "auth_base.html" %}
{% load crispy_forms_tags %}


{% block MAIN_CONTENT %} 

    <h1 class="mt-5"> </h1>
    <h1>Your message has been sent successfully!</h1>
       
{% endblock MAIN_CONTENT %}